### ISSUE TITLE
Missing required permissions and instructions on how to run 

### ISSUE THREAD

**Issue by avivdeg** [NetApp/FSx-ONTAP-samples-scripts#97]
https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Monitoring/Lun is missing the permissions prerequisites to run this CloudFormation Template

GPT4 response (I'm sure it's not correct):

Here's a general list of permissions required to run this CloudFormation template:

CloudFormation Permissions:

cloudformation:CreateStack
cloudformation:DescribeStackEvents
cloudformation:DescribeStackResources
cloudformation:GetTemplate
cloudformation:ListStackResources
cloudformation:UpdateStack
cloudformation:DeleteStack
IAM Permissions:

iam:CreateRole
iam:PutRolePolicy
iam:AttachRolePolicy
iam:PassRole
iam:DetachRolePolicy
iam:DeleteRolePolicy
iam:DeleteRole
Lambda Permissions:

lambda:CreateFunction
lambda:InvokeFunction
lambda:DeleteFunction
lambda:GetFunction
lambda:UpdateFunctionCode
lambda:UpdateFunctionConfiguration
EC2 Permissions:

ec2:CreateVpcEndpoint
ec2:CreateNetworkInterface
ec2:DescribeNetworkInterfaces
ec2:DeleteNetworkInterface
ec2:AssignPrivateIpAddresses
ec2:UnassignPrivateIpAddresses
ec2:DeleteVpcEndpoints
Secrets Manager Permissions:

secretsmanager:CreateSecret
secretsmanager:GetSecretValue
secretsmanager:DeleteSecret
CloudWatch Permissions:

cloudwatch:PutMetricData
cloudwatch:PutDashboard
cloudwatch:DeleteDashboards

Alternatively, we can recommend an IAM user to use.

**Comment by kcantrel** [comment]
Updated the README file to list the required permissions.
